keys:
  - &primary age10fa7ce7w6q0ppk5l2gvg6d02g9cmj26rpt00ct54d4latqsnwajs90a43h
  - &jellyfin age1c4sghnqh77k930j4y3z690tfpud627wz60y75440vzxk8u8hkuvs438jvl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp: []
      age:
      - *primary
      - *jellyfin
