keys:
  - &primary age1dsuede07h7akeaucp53uyxu6wa5y3yapxy3c0nh34vcdhxnanacqr6q3tc
  - &traefik age1k53pxzjtln8ds72ys5crlqz48q3flr8kawjhfmu34w4306mahscqgdamrx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/traefik/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
      - *traefik
